apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-secret.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - redis/redis-deployment.yaml
  - redis/redis-service.yaml
  - gateway/gateway-deployment.yaml
  - gateway/gateway-service.yaml
  - admin/admin-deployment.yaml
  - admin/admin-service.yaml
  - web/web-deployment.yaml
  - web/web-service.yaml
  - console/console-deployment.yaml
  - console/console-service.yaml
  - ingress.yaml
